esphome:
  name: artel-micronova-ram
  includes:
    - ram_scanner.h
  on_boot:
    priority: 600
    then:
      - lambda: |-
          init_ram_scanner();

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG
  baud_rate: 115200

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true
  min_auth_mode: WPA2
  power_save_mode: NONE

api:

ota:
  - platform: esphome

interval:
  - interval: 200ms
    then:
      - lambda: |-
          scan_next_ram();